name: Bug Report🐛

about: Create a bug report to help us improve

title: "[BUG] "
labels: bug

body:
  - type: markdown
    value: |
      **Describe the bug**
      A clear and concise description of what the bug is.

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.

  - type: input
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.

  - type: input
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior:

  - type: input
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: markdown
    value: |
      **Screenshots**
      If applicable, add screenshots to help explain your problem.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g., operating system, browser, version, etc.

  - type: markdown
    value: |
      **Additional Information**
      Add any other information about the problem here.

  - type: markdown
    value: |
      **_Before submitting the issue, make sure to remove any sensitive information._**
